[pytest]
# Tell pytest where tests live
testpaths = DataCollection/forest_gain_tiling/tests
python_files = test_*.py *_test.py
norecursedirs = .git venv env build dist
pythonpath = DataCollection/forest_gain_tiling